version: '3.4'
services:
    # Descrevendo o servi√ßo do banco de dados.
    banco:
        image: mysql:5.7
        container_name: bancomysql
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: algafood2
            MYSQL_USER: developer
            MYSQL_PASSWORD: developer        
        networks: 
            - aplicacao-network
networks:
    aplicacao-network:
        driver: bridge

# Com o container executanto para entrar e executar comandos mysql
# docker exec -it bancomysql mysql -uroot -proot